services:
  database:
    image: postgres:latest
    container_name: postgres-container-dev
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
    ports:
      - 5433:5432
