services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy_backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8181:80"
    depends_on:
      - backend
    networks:
      - app_network_backend

  backend:
    container_name: backend_service
    build:
      context: ../
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: jdbc:postgresql://database:5432/mydatabase
      DATABASE_USERNAME: dbuser
      DATABASE_PASSWORD: dbpassword
    volumes:
      - /home/italo/saver-docs:/usr/app/saver-docs
    depends_on:
      - database
    networks:
      - app_network_backend

  database:
    image: postgres:latest
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /home/italo/saverdb-v2:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network_backend

networks:
  app_network_backend:
    driver: bridge