name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Image Name
        run: echo "IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/meu-app" >> $GITHUB_ENV

      - name: DOcker Build
        run: docker build -t $IMAGE_NAME:latest .

      - name: Docker Push
        run: docker push $IMAGE_NAME:latest
